### ISSUE TITLE
[META] base distribution phase 2

### ISSUE THREAD

**Issue by oliverklee** [phpList/base-distribution#18]
This meta ticket covers the base-distribution-related tasks for phase 2. The core-specific tasks are listed in https://github.com/phpList/phplist4-core/issues/125, the rest-api-specific tasks are listed in https://github.com/phpList/rest-api/issues/20, and the web-frontend-specific-tasks are listed in https://github.com/phpList/web-frontend/issues/16.

- [x] make sure Composer installs the latest version of the dependencies (should be fixed as it was a Packagist configuration issue)
- [x] #19 remove the web-frontend dependency
- [x] #16, #20 make the package installable via `composer create-project`
- [x] #21 rename the branch alias from 4.0.0-dev to 4.0.x-dev https://getcomposer.org/doc/articles/aliases.md#branch-alias
- [x] #22, automatically set up the document root and document this
- [x] #17, #22 document the installation process
- [x] add CI stuff for this package
- [x] #24 add the symfony console
- [x] #29 prevent access to the application root directory
- [x] #30 document the Apache settings (with examples)
- [x] #25 document how to use the different application contexts
- [x] #31 use the bin/ and web/ generation script from the core
- [x] #32 set up the log and cache directories
- [x] #25, #33 document running phpList in development and testing mode
- [x] #43 automatically clear and warm all caches on composer update
- [x] #49 add a structure for a configuration file that is outside the vendor folder
- [x] document how to create downloadable tgz/zip packages
