### ISSUE TITLE
[META] phase 3

### ISSUE THREAD

**Issue by oliverklee** [phpList/base-distribution#61]
- [x] #63 provide the source code language in the code snippets in the README
- [x] #64 add a composer.lock and make sure everything is fine both with the lowest as well as highest version of the dependencies http://naderman.de/slippy/slides/2017-07-13-T3DD17-Composer-Best-Practices.pdf
- [x] debug and resolve "bad request" problem on my local Apache
- [ ] configure prefer-stable and prefer-dist
- [x] #69, #??? add system tests for all three environments
- [ ] #56 automate the creation of downloadable tgz/zip packages
- [x] make the project structure more similar to the default Symfony project structure
- [ ] research PHP-based deployment tools (Packagist installs, Github stars, Github watchers, latest release, PHP versions)
    - [ ] https://www.phing.info/ 4 863 806, 842, 67, 2016-12-22, php >= 5.2.0
    - [ ] https://deployer.org/ 847 967, 5 157, 230, 2017-12-16, php ~7.0
    - [ ] http://rocketeer.autopergamene.eu/ 253 471, 2 532, 97, 2017-01-06, php >= 5.4.0
    - [ ] https://github.com/TYPO3/Surf 63 594, 48, 16, 2016-12-12, ???
    - [ ] https://magephp.github.io/, 10 094, 11, 4, 2016-09-09, php >= 5.3
    - [ ] https://github.com/alwex/php-deploy, 205, 1, 3, 2015-03-17, ???
- [ ] add a deployment configuration
- [ ] document the deployment
